### ISSUE TITLE
no-op in eval: P_FN/P_MAC

### ISSUE THREAD

**Issue by seitokaichou** [rxi/fe#7]
In the `P_FN` and `P_MAC` case of `eval`, we set `va` to a newly allocated object containing (env . arg).
Afterwards, we call `fe_nextarg`, discarding the return value and advancing the arg-list, which contains the argument list of the funtion and the expression itself.
But the previous value of `arg` was already baked into `va`, and `arg` is not used anywhere later in `eval` (and is local to it).

Therefore, is the `fe_nextarg` line a no-op?
https://github.com/rxi/fe/blob/master/src/fe.c#L660

Recompilation with the call removed does not seem to change the behaviour of function declaration.

**Comment by rxi** [comment]
The call to `fe_nextarg` is for [checking for the existence](https://github.com/rxi/fe/blob/master/src/fe.c#L105) of an argument to `fn`:
```
> (fn)
error: too few arguments
```
Without it the above code wouldn't cause an error and the resultant function would segfault when called.

**Comment by seitokaichou** [comment]
Thanks, that makes sense now - I haven't thought of this case. 
And sorry for the noise.
